FROM ghcr.io/cirruslabs/flutter:3.29.3 AS builder
WORKDIR /app
COPY pubspec.yaml pubspec.lock ./
RUN flutter pub get
COPY . .
ARG API_URL=https://loyaltytoolor.onrender.com
RUN flutter build web --release --dart-define=API_URL=$API_URL

FROM nginx:alpine
COPY --from=builder /app/build/web /usr/share/nginx/html
COPY nginx.web.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
